name: Java CI with Gradle  #워터플로우 이름

on:
  push:  #main 브랜치에 푸쉬할때
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:  # 단계 : 마켓플레이즈에 등록된 작업
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'  #JDK 제공하는 제공자
      - name: Grant execute permission for gradlew  #gladle을 통해 실행
        run: chmod +x gradlew  # 권한을 주는 것을 실행
      - name: Build with Gradle
        run: ./gradlew build
      - name: Docker build  # 도커 jar 파일을 통해 컨테이너화 하는 것
        run: | # 도커 빌드할 때 사용하는 명령어 
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t spring-cicd . 
          docker tag spring-cicd minjik/spring-cicd:${GITHUB_SHA::7}  
          docker push minjik/spring-cicd:${GITHUB_SHA::7}
          
          # -> 빌드하고, 빌드된 이미지를 Docker Hub에 보낸다.